on:
  push:
    branches:
      - main
jobs:
  build-docker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build the portfolio Docker image
        run: docker build . --file docker/Dockerfile --tag kevin-messiaen-portfolio:$(date +%s)
